// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddSeating(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['AddSeating'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSeating(arg1) {
  return window['go']['main']['App']['DeleteSeating'](arg1);
}

export function EditCategory(arg1, arg2) {
  return window['go']['main']['App']['EditCategory'](arg1, arg2);
}

export function EditSeating(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['EditSeating'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListSeatings() {
  return window['go']['main']['App']['ListSeatings']();
}
